# Generated by Django 2.2.6 on 2019-12-10 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0002_auto_20191209_1509'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ticket',
            new_name='Compra',
        ),
    ]
